"use client";
import { useState } from "react";
import type { AnalysisResult } from "@/lib/types";
import { useT, type Lang } from "@/lib/i18n";

interface Props { result: AnalysisResult; lang: Lang; }
function buildReport(result: AnalysisResult, lang: Lang): string {
  const lines: string[] = [];
  const isZh = lang === "zh";
  lines.push("═══════════════════════════════");
  lines.push(isZh ? "   📋 简历分析报告" : "   📋 Resume Analysis Report");
  lines.push("═══════════════════════════════");
  lines.push("");
  lines.push(`${isZh ? "📊 综合评分" : "📊 Overall Score"}: ${result.overall.score}/10`);
  lines.push(`${isZh ? "📝 整体评价" : "📝 Overall Review"}: ${result.overall.summary}`);
  lines.push("");
  lines.push(isZh ? "─── 各模块分析 ───" : "─── Section Analysis ───");
  lines.push("");
  for (const s of result.sections) {
    lines.push(`▸ ${s.title}`);
    lines.push(`  ${isZh ? "优点" : "Strengths"}: ${s.strengths.join("; ")}`);
    lines.push(`  ${isZh ? "改进" : "Improvements"}: ${s.improvements.join("; ")}`);
    lines.push(`  ${isZh ? "建议" : "Suggestion"}: ${s.suggestion}`);
    lines.push("");
  }
  lines.push(isZh ? "─── 温暖的鼓励 ───" : "─── Encouragement ───");
  lines.push("");
  lines.push(`🌈 ${result.motivation}`);
  lines.push("");
  lines.push("═══════════════════════════════");
  lines.push(isZh ? "由 简历助手 App 生成" : "Generated by Resume Assistant");
  return lines.join("\n");
}

export default function ExportButton({ result, lang }: Props) {
  const t = useT(lang);
  const [copied, setCopied] = useState(false);
  function handleCopy() { navigator.clipboard.writeText(buildReport(result, lang)).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); }); }
  function handleDownload() { const blob = new Blob([buildReport(result, lang)], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `resume_report_${new Date().toISOString().slice(0, 10)}.txt`; a.click(); URL.revokeObjectURL(url); }
  return (
    <div className="flex gap-3">
      <button onClick={handleCopy} className="rounded-xl border border-gray-200/80 bg-white/90 px-5 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 hover:shadow-sm transition-all">{copied ? (lang === "zh" ? "已复制 ✓" : "Copied ✓") : t("exportCopy")}</button>
      <button onClick={handleDownload} className="rounded-xl border border-gray-200/80 bg-white/90 px-5 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 hover:shadow-sm transition-all">{t("exportDownload")}</button>
    </div>
  );
}
